version: "3.8"

services:
  KoinServer_postgres:
    image: postgres:16.1
    container_name: postgres_db
    env_file:
      - KoinServer.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "55432:5432"   # 호스트 포트 55432 → 컨테이너 내부 5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: app-koinServer
    depends_on:
      - KoinServer_postgres
    env_file:
      - KoinServer.env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}
    ports:
      - "8080:8080"

volumes:
  db_data:
